server:
  port: 8761                     # Eureka 서버의 기본 포트 번호입니다. 일반적으로 8761을 표준으로 사용합니다.

spring:
  application:
    name: pules-eureka
  cloud:
    config:
      enabled: false             # Spring Cloud Config 서버 사용을 비활성화합니다. 현재는 로컬 설정만 사용합니다. 추후 Config 서버를 도입하려면 이 부분을 true로 변경합니다.

eureka:
  instance:
    hostname: ${EC2_PUBLIC_HOSTNAME} # EC2의 퍼블릭 호스트네임을 사용 (AWS 메타데이터 활용)
    prefer-ip-address: true          # 서비스 간 통신에 IP 주소를 사용
  client:
    register-with-eureka: false      # 서버 자체는 다른 서버에 등록하지 않음
    fetch-registry: false            # 다른 서비스의 레지스트리를 가져오지 않음
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ # Eureka 서버의 URL -> Eureka 클라이언트와 통신하려면 service-url.defaultZone 값이 EC2 퍼블릭 URL을 가리키고 있어야 합니다.
  server:
    wait-time-in-ms-when-sync-empty: 0 # 레지스트리가 비어있을 때 대기 시간 0으로 설정
    enable-self-preservation: false    # 개발 초기에는 비활성화. 운영 환경에서는 반드시 true로 설정

# 로깅 설정
#logging:
#  level:
#    com.netflix.eureka: OFF       # Eureka 관련 로그를 비활성화하여 로그 출력을 줄입니다.
#    com.netflix.discovery: OFF    # 서비스 디스커버리 관련 로그를 비활성화합니다.

# 개발 단계에서는 로그 레벨을 INFO로 설정
logging:
  level:
    com.netflix.eureka: INFO
    com.netflix.discovery: INFO